version: '3'
services:
  drupal:
    image: custome_drupal
    ports:
      - "8080:80"
    volumes:
      - ./drupal-data:/var/lib/postgresql/data
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal